In [2]:
from helpers import get_sample_file
import pandas as pd

In [3]:
df = get_sample_file(top_1000=True)

In [5]:
df['test'] = 'test'

In [6]:
df

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,test
0,C09E4093905089BD,classic_bike,2022-07-23 11:34:57,2022-07-23 11:45:08,Melrose St & Broadway,4801.04,Myrtle Ave & Grove St,4816.05,40.697481,-73.935877,40.699050,-73.915160,member,test
1,374630DB5822C392,electric_bike,2022-07-29 18:19:08,2022-07-29 18:26:50,E 68 St & 3 Ave,6896.16,E 85 St & York Ave,7146.04,40.767128,-73.962246,40.775369,-73.948034,member,test
2,4F73CA25880A1215,electric_bike,2022-07-16 16:30:58,2022-07-16 17:39:18,W 37 St & 10 Ave,6611.02,Knickerbocker Ave & Cooper St,4582.05,40.756604,-73.997901,40.690810,-73.904480,member,test
3,ECD6EE19C0CC1D31,electric_bike,2022-07-17 17:35:57,2022-07-17 18:03:36,W 37 St & 10 Ave,6611.02,6 Ave & Broome St,5610.09,40.756604,-73.997901,40.724310,-74.004730,member,test
4,44D0987673B9997D,classic_bike,2022-07-11 07:56:29,2022-07-11 07:59:15,E 68 St & 3 Ave,6896.16,E 66 St & Madison Ave,6969.08,40.767128,-73.962246,40.768009,-73.968453,member,test
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,0F87E6AA53284B9F,classic_bike,2022-07-04 13:37:48,2022-07-04 13:44:31,34 St & 35 Ave,6605.08,Steinway St & Broadway,6711.13,40.756933,-73.926223,40.759058,-73.918975,casual,test
996,3B433CD081477953,electric_bike,2022-07-24 04:47:36,2022-07-24 05:00:46,East End Ave & E 86 St,7113.08,West End Ave & W 94 St,7524.09,40.775186,-73.944461,40.794165,-73.974124,member,test
997,5CFE90B3DCDFC7DE,classic_bike,2022-07-02 20:21:59,2022-07-02 20:29:46,East End Ave & E 86 St,7113.08,E 75 St & 3 Ave,6991.12,40.775186,-73.944461,40.771129,-73.957723,member,test
998,EC034412314B3701,electric_bike,2022-07-01 07:39:09,2022-07-01 07:51:09,Washington Pl & Broadway,5755.01,Madison Av & E 51 St,6659.09,40.729039,-73.994046,40.758630,-73.975130,member,test
999,8B2AA9CC110BBC8A,classic_bike,2022-07-31 17:03:40,2022-07-31 17:15:57,Carroll St & Franklin Ave,3847.04,7 St & 5 Ave,3914.02,40.667955,-73.958703,40.670492,-73.985417,member,test

In [ ]:
df_full.dtypes

In [ ]:
df2 = df_full.groupby(['start_station_id'])\
[['start_lat', 'start_lng', 'started_at', 'ended_at', 'start_station_name']]\
.agg({'start_station_name': 'min', 'start_lat': 'mean', 'start_lng': 'mean', 'started_at': 'min', 'ended_at': 'max'})

In [ ]:
current_stations = pd.read_sql_table('stations', schema='prod', con=verbose_engine)

In [ ]:
current_stations = current_stations.astype({'station_name': 'string', 'citi_station_id': 'string'})

In [ ]:
current_stations.set_index(['station_name', 'citi_station_id'])

In [ ]:
df2.index.names = ['citi_station_id']

In [ ]:
df2

In [ ]:
{x.pop('citi_station_id'): x for x in df2.reset_index().to_dict('records')}